[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "radar"
authors = [{name = "nrb5089", email = "nrb5089@gmail.com"}]
dynamic = ["version", "description"]