[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "radar"
authors = [{name = "Blinn", email = "myemail@email.com"}]
dependencies = [
    "numpy",
    "scipy",
    "opencv-python",
    "matplotlib"
]
dynamic = ["version", "description"]